---
services:
  app:
    image: nextcloud:30.0.2-fpm-alpine
    restart: always
    env_file: .env
    volumes:
      - nextcloud-data:/var/www/html
    depends_on:
      - db
      - redis
  caddy:
    image: caddy:2.8.4-alpine
    restart: always
    volumes:
      - nextcloud-data:/var/www/html:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 3004:80
  db:
    image: postgres:16.4-alpine
    restart: always
    env_file: .env
    ports:
      - 127.0.0.1:6902:5432
    volumes:
      - nextcloud-postgres:/var/lib/postgresql/data
  redis:
    image: valkey/valkey:8.0.1-alpine
    restart: always

volumes:
  nextcloud-data:
    driver: local
  nextcloud-postgres:
    driver: local
